name: deprem_harita_proje
description: Kandilli rasathanesi son 50 depremin harita üzerinde gösterimi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.4
  cupertino_icons: ^1.0.2
  #state
  flutter_mobx: ^2.0.2
  mobx: ^2.0.5
  mobx_codegen: ^2.1.1
  provider: ^6.0.1
  #map
  custom_info_window: ^1.0.1
  google_maps_flutter: ^2.2.5
  bubble: ^1.2.1
  change_app_package_name: ^1.1.0
  freezed: ^2.3.2
  easy_localization: ^3.0.1
  dio: ^4.0.6
  get_it: ^7.2.0
  url_launcher: ^6.1.7
  flutter_svg: ^1.1.6
  build_runner: ^2.3.2
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  retrofit_generator: ^4.2.0
  device_preview: ^1.1.0
  smooth_page_indicator: ^1.0.1
  shared_preferences: ^2.0.18
  cached_network_image: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0


flutter:

  uses-material-design: true
  
  assets:
    - assets/lang/
    - assets/svg/
    - assets/svg/map/
    - assets/image/
    - assets/lottie/
    - assets/icon/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: MontserratBlack
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: MontserratBlackItalic
      fonts:
        - asset: fonts/Montserrat-BlackItalic.ttf
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: MontserratBoldItalic
      fonts:
        - asset: fonts/Montserrat-BoldItalic.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: MontserratExtraBoldItalic
      fonts:
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
    - family: MontserratExtraLightItalic
      fonts:
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
    - family: MontserratItalic
      fonts:
        - asset: fonts/Montserrat-Italic.ttf
    - family: MontserratLight
      fonts:
        - asset: fonts/Montserrat-Light.ttf    
    - family: MontserratLightItalic
      fonts:
        - asset: fonts/Montserrat-LightItalic.ttf
    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: MontserratMediumItalic
      fonts:
        - asset: fonts/Montserrat-MediumItalic.ttf    
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf               
    - family: MontserratSemiBoldItalic
      fonts:
        - asset: fonts/Montserrat-SemiBoldItalic.ttf    
    - family: MontserratThin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: MontserratThinItalic
      fonts:
        - asset: fonts/Montserrat-ThinItalic.ttf

